# Workflow to build and push Caddy Docker image to GitHub Container Registry
name: Build caddy-cloudflare-geoip-ratelimit

# Controls when the action will run
on:
  workflow_dispatch:  # allows to run the workflow manually from the Actions tab
  push:
    branches: main
    paths:
      - caddy-cloudflare-geoip-ratelimit/Dockerfile

# Permissions needed for this workflow
permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    with:
      docker_name: caddy-cloudflare-geoip-ratelimit
      docker_description: "Caddy Docker custom build with Cloudflare GeoIP and Rate Limit modules"
      version_regex: 'caddy:\K[0-9]+\.[0-9]+\.[0-9]+$'
      platforms: linux/amd64
