# Workflow to build and push Beszel Docker image to GitHub Container Registry
name: Build beszel

# Controls when the action will run
on:
  workflow_dispatch:  # allows to run the workflow manually from the Actions tab
  push:
    branches: main
    paths:
      - beszel/Dockerfile

# Permissions needed for this workflow
permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    with:
      docker_name: beszel
      docker_description: "Beszel Docker image with Kamal service label"
      version_regex: 'ghcr\.io/henrygd/beszel/beszel:\K[0-9]+\.[0-9]+\.[0-9]+'
      platforms: linux/amd64
